version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  web:
    build: .
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db